spring:
  profiles:
    active: production
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: ${sky.datasource.url}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #Mybatis log
    map-underscore-to-camel-case: true #camel naming auto case
  mapper-locations: classpath:mapper/*.xml

sky:
  jwt:
    #jwt sign key
    admin-secret-key: ${sky.jwt.admin-secret-key}
    #jwt expire time
    admin-ttl: ${sky.jwt.admin-ttl}
    #token name from front end
    admin-token-name: ${sky.jwt.admin-token-name}
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: ${sky.jwt.user-ttl}
    user-token-name: ${sky.jwt.user-token-name}
  oss:
    endpoint: ${sky.oss.endpoint}
    access-key-id: ${sky.oss.access-key-id}
    access-key-secret: ${sky.oss.access-key-secret}
    bucket-name: ${sky.oss.bucket-name}

#log for transaction
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

